-- SCRIPT DE CRIAÇÃO DAS TABELAS - FÁBRICA DE CHOCOLATE

CREATE TABLE Responsavel_Crianca (
    CPF_CRIANCA VARCHAR2(11) PRIMARY KEY, 
    CPF_RESPONSAVEL VARCHAR2(11) UNIQUE NOT NULL, -- Chave alternativa
    Nome_Crianca VARCHAR2(100) NOT NULL,
    Nome_Responsavel VARCHAR2(100) NOT NULL,
    Data_Nascimento_Crianca DATE,
    Data_Nascimento_Responsavel DATE,
    End_cep VARCHAR2(8),
    End_rua VARCHAR2(100),
    End_bairro VARCHAR2(50),
    End_estado VARCHAR2(50)
);

CREATE TABLE Fabrica (
    CNPJ VARCHAR2(14) PRIMARY KEY,
    Data_Fundacao DATE
);

CREATE TABLE Ingrediente (
    COD VARCHAR2(10) PRIMARY KEY,
    Nome VARCHAR2(100) UNIQUE NOT NULL,
    Marca VARCHAR2(50)
);

CREATE TABLE Chocolate (
    ID VARCHAR2(10) PRIMARY KEY,
    Nome VARCHAR2(100) UNIQUE NOT NULL,
    Tipo VARCHAR2(50),
    Data_Validade DATE,
    CPF_CRIANCA VARCHAR2(11),
    CONSTRAINT FK_CHOC_CRIANCA FOREIGN KEY (CPF_CRIANCA) REFERENCES Responsavel_Crianca(CPF_CRIANCA)
);

CREATE TABLE Funcionario (
    CPF VARCHAR2(11) PRIMARY KEY,
    Nome VARCHAR2(100) NOT NULL,
    Salario NUMBER(10,2),
    CPF_CHEFE VARCHAR2(11),
    CONSTRAINT FK_FUNC_SUPERVISOR FOREIGN KEY (CPF_CHEFE) REFERENCES Funcionario(CPF)
);

CREATE TABLE Setor (
    CNPJ_Fabrica VARCHAR2(14),
    COD_SETOR VARCHAR2(10),
    Nome VARCHAR2(50) NOT NULL,
    Finalidade VARCHAR2(200) NOT NULL,
    Data_Criacao DATE,
    CONSTRAINT PK_SETOR PRIMARY KEY (CNPJ_Fabrica, COD_SETOR),
    CONSTRAINT FK_SETOR_FABRICA FOREIGN KEY (CNPJ_Fabrica) REFERENCES Fabrica(CNPJ)
);

CREATE TABLE Maquina (
    ID VARCHAR2(10) PRIMARY KEY,
    Modelo VARCHAR2(50),
    Data_Instalacao DATE,
    CNPJ_Fabrica_Setor VARCHAR2(14) NOT NULL,
    COD_Setor VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_MAQUINA_SETOR FOREIGN KEY (CNPJ_Fabrica_Setor, COD_Setor) REFERENCES Setor(CNPJ_Fabrica, COD_Setor)
);

CREATE TABLE OompaLoompa (
    CPF_FUNCIONARIO VARCHAR2(11) PRIMARY KEY,
    Tribo VARCHAR2(50),
    CONSTRAINT FK_OOMPA_FUNC FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES Funcionario(CPF)
);

CREATE TABLE Pessoa (
    CPF_FUNCIONARIO VARCHAR2(11) PRIMARY KEY,
    Profissao VARCHAR2(50),
    CONSTRAINT FK_PESSOA_FUNC FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES Funcionario(CPF)
);

CREATE TABLE Contatos (
    CPF_CRIANCA VARCHAR2(11),
    Contatos VARCHAR2(100),
    CONSTRAINT PK_CONTATOS PRIMARY KEY (CPF_CRIANCA, Contatos),
    CONSTRAINT FK_CONTATOS_CRIANCA FOREIGN KEY (CPF_CRIANCA) REFERENCES Responsavel_Crianca(CPF_CRIANCA)
);

CREATE TABLE Visita (
    CPF_CRIANCA VARCHAR2(11),
    CNPJ_FABRICA VARCHAR2(14),
    Data_Visita DATE,
    CONSTRAINT PK_VISITA PRIMARY KEY (CPF_CRIANCA, CNPJ_FABRICA, Data_Visita),
    CONSTRAINT FK_VISITA_CRIANCA FOREIGN KEY (CPF_CRIANCA) REFERENCES Responsavel_Crianca(CPF_CRIANCA),
    CONSTRAINT FK_VISITA_FABRICA FOREIGN KEY (CNPJ_FABRICA) REFERENCES Fabrica(CNPJ)
);

CREATE TABLE Acidente (
    ID VARCHAR2(10) PRIMARY KEY,
    Data_Acidente DATE NOT NULL,
    Gravidade VARCHAR2(50),
    Musica VARCHAR2(100),
    CPF_CRIANCA_VISITA VARCHAR2(11) NOT NULL,
    CNPJ_FABRICA_VISITA VARCHAR2(14) NOT NULL,
    Data_Visita DATE NOT NULL,
    CONSTRAINT FK_ACID_VISITA FOREIGN KEY (CPF_CRIANCA_VISITA, CNPJ_FABRICA_VISITA, Data_Visita) REFERENCES Visita(CPF_CRIANCA, CNPJ_FABRICA, Data_Visita)
);

CREATE TABLE PRODUZ (
    ID_CHOCOLATE VARCHAR2(10),
    CPF_OOMPALOOMPA VARCHAR2(11),
    ID_MAQUINA VARCHAR2(10),
    CONSTRAINT PK_PRODUZ PRIMARY KEY (ID_CHOCOLATE, CPF_OOMPALOOMPA, ID_MAQUINA),
    CONSTRAINT FK_PRODUZ_CHOC FOREIGN KEY (ID_CHOCOLATE) REFERENCES Chocolate(ID),
    CONSTRAINT FK_PRODUZ_OOMPA FOREIGN KEY (CPF_OOMPALOOMPA) REFERENCES OompaLoompa(CPF_FUNC),
    CONSTRAINT FK_PRODUZ_MAQ FOREIGN KEY (ID_MAQUINA) REFERENCES Maquina(ID)
);

CREATE TABLE USA (
    ID_CHOCOLATE VARCHAR2(10),
    COD_INGREDIENTE VARCHAR2(10),
    CONSTRAINT PK_USA PRIMARY KEY (ID_CHOCOLATE, COD_INGREDIENTE),
    CONSTRAINT FK_USA_CHOC FOREIGN KEY (ID_CHOCOLATE) REFERENCES Chocolate(ID),
    CONSTRAINT FK_USA_INGR FOREIGN KEY (COD_INGREDIENTE) REFERENCES Ingrediente(COD)
);